name: CI

on: [push]

jobs:
  build:
    runs-on:
    - ubuntu-latest
    - centos-latest

    strategy:
      matrix:
        packages:
        - terraform

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      if: contains(job.container.image, 'ubuntu')
      run: |
        sudo apt-get -y update
        sudo apt-get -y install build-essential ruby ruby-dev bundler

    - name: Install dependencies
      if: contains(job.container.image, 'centos')
      run: |
        sudo yum instal ruby ruby-devel rubygem-bundler -y
        sudo yum groupinstall 'Development Tools' -y

    - name: Install fpm-cookery
      run: |
        sudo gem install fpm-cookery

