name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DATADOG_TOKEN: ${{ secrets.DATADOG_TOKEN }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install build-essential ruby ruby-dev bundler git dpkg-dev

    - name: Install fpm-cookery
      run: |
        sudo gem install fpm-cookery

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build package
      id: build_package
      run: |
        ./build.sh

    - name: Checkout pages to repository
      uses: actions/checkout@v2
      with:
        repository: 'caquino/caquino.github.io'
        path: 'caquino.github.io'
        token: ${{ secrets.PAT }}

    - name: Push package to repository
      run: |
        ./deploy.sh

    - name: Submit metrics
      uses: masci/datadog@v1
      with:
        api-key: ${{ secrets.DATADOG_TOKEN }}
        metrics: |
          - type: "count"
            name: "ci.runs.count"
            value: 1.0
            host: ${{ github.repository_owner }}
            tags:
              - "project:${{ github.repository }}"
              - "branch:${{ github.head_ref }}"

    - name: Submit failure event
      if: failure()
      uses: masci/datadog@v1
      with:
        api-key: ${{ secrets.DATADOG_TOKEN }}
        events: |
          - title: "Failed build"
            text: "Branch ${{ github.head_ref }} failed to build"
            alert_type: "error"
            host: ${{ github.repository_owner }}
            tags:
              - "project:${{ github.repository }}"
              - "branch:${{ github.head_ref }}"

  metrics:
    runs-on: ubuntu-latest
    name: Collect Metrics
    needs: [build]
    if: always()

    steps:
      - name: Collect metrics
        uses: konsentus/action.collect-build-metrics@v1.0.1
        with:
          send_to_dd: 'true'
          save_to_fs: 'true'
          datadog_url_location: 'com'
          filename: 'build-metrics.json'

      - name: Upload to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-metrics
          path: build-metrics.json
