name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DATADOG_TOKEN: ${{ secrets.DATADOG_TOKEN }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 11 * * *'

jobs:
  deps:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install build-essential ruby ruby-dev bundler git dpkg-dev

    - name: Install fpm-cookery
      run: |
        sudo gem install fpm-cookery

  checkout:
    name: Checkout repository
    - name: Checkout
      uses: actions/checkout@v2

  build:
    name: Build packages
    - name: Build package
      id: build_package
      run: |
        ./build.sh

  deploy:
    name: Deploy to destination
    - name: Checkout pages to repository
      uses: actions/checkout@v2
      with:
        repository: 'caquino/caquino.github.io'
        path: 'caquino.github.io'
        token: ${{ secrets.PAT }}

    - name: Push package to repository
      run: |
        ./deploy.sh

  metrics:
    runs-on: ubuntu-latest
    name: Collect Metrics
    needs: [build]
    if: always()

    steps:

    - name: Collect metrics
      uses: konsentus/action.collect-build-metrics@v1.0.0
      with:
        send_to_dd: 'true'
        datadog_url_location: 'com'
