name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install build-essential ruby ruby-dev bundler git dpkg-dev

    - name: Install fpm-cookery
      run: |
        sudo gem install fpm-cookery

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build package
      id: build_package
      run: |
        ./build.sh

    - name: Checkout pages to repository
      uses: actions/checkout@v2
      with:
        repository: 'caquino/caquino.github.io'
        path: 'caquino.github.io'
        token: ${{ secrets.PAT }}

    - name: Push package to repository
      run: |
        ./deploy.sh
