name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DATADOG_TOKEN: ${{ secrets.DATADOG_TOKEN }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install build-essential ruby ruby-dev bundler git dpkg-dev

    - name: Install fpm-cookery
      run: |
        sudo gem install fpm-cookery

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build package
      id: build_package
      run: |
        ./build.sh

    - name: Checkout pages to repository
      uses: actions/checkout@v2
      with:
        repository: 'caquino/caquino.github.io'
        path: 'caquino.github.io'
        token: ${{ secrets.PAT }}

    - name: Push package to repository
      run: |
        ./deploy.sh

  metrics:
    runs-on: ubuntu-latest
    name: Collect Metrics
    needs: [build]
    if: always()

    steps:

    - name: Collect metrics
      uses: konsentus/action.collect-build-metrics@v1.0.1
      with:
        send_to_dd: 'true'
        save_to_fs: 'true'
        datadog_url_location: 'com'
        filename: 'build-metrics.json'

    - name: Upload to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-metrics
        path: build-metrics.json
