name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        packages:
        - terraform

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install build-essential ruby ruby-dev bundler

    - name: Install fpm-cookery
      run: |
        sudo gem install fpm-cookery

